# Generated by Django 2.1.1 on 2018-09-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20180929_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='torrents',
            field=models.ManyToManyField(blank=True, to='movies.Torrent'),
        ),
    ]
